track: web-dev
learningObjectives:
  - java
  - hibernate
  - spring
  - db/modeling
  - db/connection
  - db/indexes-constraints
  - sql/tables
  - sql/crud
  - sql/drop
  - postgres/psql
  - postgres/data-types
  - postgres/dump-restore
  - postgres/indexes

